# Generated by Django 3.2.6 on 2021-08-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_cycle', models.BooleanField(default=False)),
                ('is_tree', models.BooleanField(default=False)),
                ('is_PST', models.BooleanField(default=False)),
                ('is_bipartite', models.BooleanField(default=False)),
                ('is_multipartite', models.BooleanField(default=False)),
                ('is_star', models.BooleanField(default=False)),
                ('is_path', models.BooleanField(default=False)),
                ('is_hamiltonian', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.TextField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidence_matrix', to='graph.graph')),
            ],
        ),
        migrations.CreateModel(
            name='AdjacencyMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.TextField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_matrix', to='graph.graph')),
            ],
        ),
    ]
